server:
  port: 9005
spring:  application:    name: micro-zuul
eureka:  client:    serviceUrl:      defaultZone: http://localhost:9000/eureka
      
zuul:  routes:    api-a: 
      path: /enq/**
      serviceId: micro-user
    api-b:
      path: /enq/**
      serviceId: micro-ribbon
    