spring:
  application:
    name: spring-config-server  cloud:    config:      server:        git:          uri: https://github.com/flyingzh/spring-cloud-config/
          searchPaths: config-repo
          username: 
          password: 
      label: master
                
server:  port: 8888

eureka:  client:    serviceUrl:
      defaultZone: http://localhost:9000/eureka/      
  